.PHONY: clean All

All:
	@echo "----------Building project:[ ffmpeg3_1_1 - Debug ]----------"
	@$(MAKE) -f  "ffmpeg3_1_1.mk"
clean:
	@echo "----------Cleaning project:[ ffmpeg3_1_1 - Debug ]----------"
	@$(MAKE) -f  "ffmpeg3_1_1.mk" clean
